from config.constants import MGMT_ACCOUNT_ID, HOME, DEV_ACCOUNT_ID

# OKTA Constants
OKTA_BASE_URL = "dev-216899.okta.com"
OKTA_INTEGRATED_AWS_ACCOUNT_ID = DEV_ACCOUNT_ID
OKTA_FACTOR = "GOOGLE"
OKTA_APP_LINK = "https://dev-216899.okta.com/home/amazon_aws/0oaaqxeiciFB6fssP4x6/272"
OKTA_SESSION_DURATION = 43200
OKTA_PROVIDER_NAME = "OKTA"
OKTA_PRINCIPAL_ARN = f"arn:aws:iam::{OKTA_INTEGRATED_AWS_ACCOUNT_ID}:saml-provider/{OKTA_PROVIDER_NAME}"
FIGGY_KEYRING_NAMESPACE = "figgy"
FIGGY_KEYRING_ASSERTION_NAME = "okta_assertion"
OKTA_SESSION_CACHE_PATH = f"{HOME}/.figgy/devops/cache/okta/session"


