name: Build

on:
  push:
    branches: [master, build]
  pull_request:
    branches: [master, build]

jobs:
  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build
        run: |
          echo "MacOs build is happening!!!"
          cd cli
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          pip3 install -r requirements-darwin.txt

          echo "Building figgy onedir"
          # pyinstaller figcli/__main__.py --onedir --hiddenimport configparser --hiddenimport keyrings --hiddenimport keyring.backends  --hiddenimport pkg_resources.py2_warn
          pyinstaller figgy.spec

          mv dist/__main__/__main__ dist/__main__/figgy
          scripts/zip_it.sh
          scripts/tar_it.sh $(scripts/get_version.sh)

      - name: Test Artifact
        env:
          OVERRIDE_KEYRING: true
          FIGGY_DISABLE_KEYRING: true
          OKTA_SSO_USER: ${{ secrets.OKTA_SSO_USER }}
          OKTA_SSO_PASSWORD: ${{ secrets.OKTA_SSO_PASSWORD }}
          OKTA_EMBED_URL: ${{ secrets.OKTA_EMBED_URL }}
          OKTA_MFA_SECRET: ${{ secrets.OKTA_MFA_SECRET }}
          DEV_AUDIT_DISABLED: true
          DEV_SYNC_DISABLED: true
        run: |
          echo "Adding figgy binary to path"
          cd cli/dist/__main__/
          export PATH="$PATH:$(PWD)"
          figgy --version

          #cd ../../

          #echo "Testing MAC binary as okta user"
          #python run_tests.py okta

      - name: Get Version
        id: version
        run: |
          cd cli
          # Parse version
          VERSION=$(./scripts/get_version.sh)
          echo "Setting release version to $VERSION"
          echo "::set-env name=RELEASE_VERSION::$VERSION"

      - name: Deploy
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_DEFAULT }}
          CREDENTIALS_FILE: ${{ secrets.CREDENTIALS_DEPLOY }}
          VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          mkdir -p ~/.aws
          echo "$CONFIG_FILE" > ~/.aws/config
          echo "$CREDENTIALS_FILE" > ~/.aws/credentials

          dest="s3://figgy-website/releases/cli/latest/darwin/figgy.zip"
          aws s3 cp cli/figgy.zip $dest

          echo "Deploying darwin figgy to s3://figgy-website/releases/cli/${VERSION}/darwin/figgy.zip"
          aws s3 cp cli/figgy.zip "s3://figgy-website/releases/cli/${VERSION}/darwin/figgy.zip"

          echo "Deploying darwin figgy to s3://figgy-website/releases/cli/latest/darwin/figgy.tar.gz"
          aws s3 cp cli/figgy.tar.gz s3://figgy-website/releases/cli/latest/darwin/figgy.tar.gz

          echo "Deploying darwin figgy to s3://figgy-website/releases/cli/${VERSION}/darwin/figgy.tar.gz"
          aws s3 cp cli/figgy.tar.gz "s3://figgy-website/releases/cli/${VERSION}/darwin/figgy.tar.gz"

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
          freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev

      - name: Build
        run: |
          echo "Linux build is happening!!!"
          # install requirements

          cd cli
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          pip3 install -r requirements-linux.txt

          pyinstaller figgy.spec

          mv dist/__main__/__main__ dist/__main__/figgy
          scripts/zip_it.sh
          scripts/tar_it.sh $(scripts/get_version.sh)


      - name: Test Artifact
        env:
          FIGGY_DISABLE_KEYRING: "true"
          OVERRIDE_KEYRING: "true"
        run: |
          export TERM=linux
          export TERMINFO=/etc/terminfo

          echo "Adding figgy binary to path"
          cd cli/dist/__main__/
          echo "PATH: $PATH"
          export "PATH=$PATH:$(pwd)"
          echo "PATH: $PATH"
          cd ../../

          echo "Testing Linux binary as bastion user"
          python run_tests.py bastion

      - name: Get Version
        id: version
        run: |
          cd cli
          # Parse version
          VERSION=$(./scripts/get_version.sh)
          echo "Setting release version to $VERSION"
          echo "::set-env name=RELEASE_VERSION::$VERSION"

      - name: Deploy
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_DEFAULT }}
          CREDENTIALS_FILE: ${{ secrets.CREDENTIALS_DEPLOY }}
          VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          mkdir -p ~/.aws
          echo "$CONFIG_FILE" > ~/.aws/config
          echo "$CREDENTIALS_FILE" > ~/.aws/credentials

          echo "Deploying linux figgy to $dest"
          aws s3 cp cli/figgy.zip s3://figgy-website/releases/cli/latest/linux/figgy.zip

          echo "Deploying linux figgy to s3://figgy-website/releases/cli/${VERSION}/linux/figgy.zip"
          aws s3 cp cli/figgy.zip "s3://figgy-website/releases/cli/${VERSION}/linux/figgy.zip"

          echo "Deploying linux figgy to s3://figgy-website/releases/cli/latest/linux/figgy.tar.gz"
          aws s3 cp cli/figgy.tar.gz s3://figgy-website/releases/cli/latest/linux/figgy.tar.gz

          echo "Deploying linux figgy to s3://figgy-website/releases/cli/${VERSION}/linux/figgy.tar.gz"
          aws s3 cp cli/figgy.tar.gz "s3://figgy-website/releases/cli/${VERSION}/linux/figgy.tar.gz"


  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build
        shell: bash
        run: |
          echo "Windows build is happening!!!"
          # install requirements

          cd cli
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          pip3 install -r requirements-windows.txt

          pyinstaller figgy.spec

          mv dist/__main__/__main__.exe dist/__main__/figgy.exe
          scripts/tar_it.sh $(scripts/get_version.sh)

      - name: Zip
        run: |
          echo "Zipping!"
          cd cli/dist/__main__/
          Compress-Archive . figgy.zip
          mv figgy.zip ../../

      - name: Test Artifact
        run: |
          echo "Adding figgy binary to path"
          cd cli/dist/__main__/
          $env:path += ";."

          echo "NORMAL VERSION NOW"
          figgy --version

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        shell: bash
        run: |
          VERSION=$(./cli/scripts/get_version.sh)
          echo "Setting release version to $VERSION"

          mkdir -p ~/.aws
          cd cli/

          echo "Deploying windows figgy to s3://figgy-website/releases/cli/latest/windows/figgy.zip"
          aws s3 cp figgy.zip "s3://figgy-website/releases/cli/latest/windows/figgy.zip"

          echo "Deploying windows figgy to s3://figgy-website/releases/cli/${VERSION}/windows/figgy.zip"
          aws s3 cp figgy.zip "s3://figgy-website/releases/cli/${VERSION}/windows/figgy.zip"

          echo "Deploying windows figgy to s3://figgy-website/releases/cli/latest/windows/figgy.tar.gz"
          aws s3 cp figgy.tar.gz "s3://figgy-website/releases/cli/latest/windows/figgy.tar.gz"

          echo "Deploying windows figgy to s3://figgy-website/releases/cli/${VERSION}/windows/figgy.tar.gz"
          aws s3 cp figgy.tar.gz "s3://figgy-website/releases/cli/${VERSION}/windows/figgy.tar.gz"
