name: Build & Test

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build_mac:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew uninstall python
          brew install awscli
          brew install python3

      - name: Build
        run: |
            echo "MacOs build is happening!!!"
            cd cli
            pip3 install pyinstaller
            pip3 install -r requirements.txt
            pip3 install -r requirements-darwin.txt
            
            ## Build OneDir
            echo "Deploying OSX figgy to $dest"
            aws s3 cp dist/figgy $dest
            rm dist/figgy

            echo "Building figgy onedir"
            pyinstaller figcli/entrypoint/cli.py --onedir --log-level=DEBUG --hiddenimport configparser --hiddenimport keyrings --hiddenimport keyring.backends --hiddenimport pycrypto  --hiddenimport pkg_resources.py2_warn
            cd dist/figgy
            zip -r figgy.zip .

            dest="s3://figgy-website/releases/cli/latest/darwin/figgy.zip"
            aws s3 cp figgy.zip $dest

#
#
#  build_linux:
#      runs-on: ubuntu-latest
#      steps:
#        - uses: actions/checkout@v2
#        - name: Set up Python 3.8
#          uses: actions/setup-python@v2
#          with:
#            python-version: 3.8
#        - name: Install dependencies
#          env:
#            FIGGY_TEST: true
#          run: |
#            sudo apt-get update \
#            && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
#            freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev
#
#        - name: Install figgy
#          run: |
#            cd cli
#            pip install -r requirements.txt
#            pip install -r requirements-linux.txt
#            scripts/install.sh
#
#        - name: Run E2E Test Suite
#          run: |
#            export TERM=linux
#            export TERMINFO=/etc/terminfo
#            cd cli
#            python run_tests.py bastion
