name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7

    - name: Get Version
      id: version
      run: |
        cd src
        # Parse version
        VERSION=$(scripts/get_version.sh)
        echo "Setting release version to $VERSION"
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Prep Release
      id: prep
      run: |
        cd src
        # Parse version
        VERSION=$(../scripts/get_version.sh)
        echo "Setting release version to $VERSION"
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

        # Parse changelog
        CHANGELOG=$(../scripts/parse_changelog.sh)
        CHANGELOG="${CHANGELOG//'%'/'%25'}"
        CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
        CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"

        echo "Got changelog: $CHANGELOG"
        echo "::set-output name=changelog::$CHANGELOG"

    - name: Create Release
      id: create_release
      uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        body: ${{ steps.prep.outputs.changelog }}
        draft: false
        prerelease: true
